controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
test_ar:
    path: /afficher/ar
    controller: App\Controller\TestController::tfarrej